sudo: false
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox -r
after_success:
  - coveralls


# I am currently not sure how we want to generate documentation for github projects
