service: TagBotGitLab
plugins:
  - serverless-python-requirements
package:
  exclude:
    - ./**
  include:
    - ./tagbotgitlab/tagbot.py
    - ./tagbotgitlab/changelog.py
    - ./tagbotgitlab/template.md
provider:
  name: aws
  runtime: python3.8
  environment:
    AUTOMATIC_MERGE: ${env:AUTOMATIC_MERGE}
    GITLAB_URL: ${env:GITLAB_URL}
    GITLAB_API_TOKEN: ${env:GITLAB_API_TOKEN}
    GITLAB_WEBHOOK_TOKEN: ${env:GITLAB_WEBHOOK_TOKEN}
    REGISTRATOR_ID: ${env:REGISTRATOR_ID}
functions:
  gitlab:
    handler: tagbotgitlab/tagbot.handler
    events:
      - http:
          path: gitlab
          method: post
custom:
  pythonRequirements:
    usePoetry: false
